CC=gcc

build: quickSort.c testSort.c ../random/random.c ../sortUtils.c
	$(CC) -o quickSort quickSort.c testSort.c ../random/random.c ../sortUtils.c

debug: quickSort.c testSort.c ../random/random.c ../sortUtils.c
	$(CC) -g -o quickSort quickSort.c testSort.c ../random/random.c ../sortUtils.c