build: bubbleSort.c testSort.c ../random/random.c
	gcc -o bubbleSort bubbleSort.c testSort.c ../random/random.c

debug: bubbleSort.c testSort.c ../random/random.c
	gcc -g -o bubbleSort bubbleSort.c testSort.c ../random/random.c
