build: selectionSort.c testSort.c ../random/random.c
	gcc -o selectionSort selectionSort.c testSort.c ../random/random.c

debug: selectionSort.c testSort.c ../random/random.c
	gcc -g -o selectionSort selectionSort.c testSort.c ../random/random.c
