build: selectionSort.c testSort.c ../random/random.c ../sortUtils.c
	gcc -o selectionSort selectionSort.c testSort.c ../random/random.c ../sortUtils.c

debug: selectionSort.c testSort.c ../random/random.c ../sortUtils.c
	gcc -g -o selectionSort selectionSort.c testSort.c ../random/random.c ../sortUtils.c
