build: insertionSort.c testSort.c ../random/random.c
	gcc -o insertionSort insertionSort.c testSort.c ../random/random.c

debug: insertionSort.c testSort.c ../random/random.c
	gcc -g -o insertionSort insertionSort.c testSort.c ../random/random.c
