build: bubbleSort.c testSort.c ../random/random.c ../sortUtils.c
	gcc -o bubbleSort bubbleSort.c testSort.c ../random/random.c ../sortUtils.c

debug: bubbleSort.c testSort.c ../random/random.c ../sortUtils.c
	gcc -g -o bubbleSort bubbleSort.c testSort.c ../random/random.c ../sortUtils.c
