build: insertionSort.c testSort.c ../random/random.c ../sortUtils.c
	gcc -o insertionSort insertionSort.c testSort.c ../random/random.c ../sortUtils.c

debug: insertionSort.c testSort.c ../random/random.c ../sortUtils.c
	gcc -g -o insertionSort insertionSort.c testSort.c ../random/random.c ../sortUtils.c
