CC=gcc

build: mergeSort.c testSort.c ../random/random.c ../sortUtils.c
	$(CC) -o mergeSort mergeSort.c testSort.c ../random/random.c ../sortUtils.c

debug: mergeSort.c testSort.c ../random/random.c ../sortUtils.c
	$(CC) -g -o mergeSort mergeSort.c testSort.c ../random/random.c ../sortUtils.c