CC=gcc ##'C:/Program Files (x86)/Dev-Cpp/MinGW64/bin/gcc.exe'
GCCFLAGS=-Wall -g

##################### TASKS #####################

TEST: DOUBLE_STACK
	$(CC) -c testTwoStack.c

DOUBLE_STACK:
	$(CC) $(GCCFLAGS) -c twoStack.c
